### ISSUE TITLE
support for `~` path

### ISSUE THREAD

**Issue by vic1707** [vic1707/Tree-plus-plus#11]

**Comment by glcraft** [comment]
j'arrive 10 ans après la guerre 😂
Mais j'ai été confronté à la meme chose pour [aio](https://github.com/glcraft/aio).

En premier lieu j'ai été voir du coté de la doc std. Je suis tombé sur la fonction [std::env::home_dir](https://doc.rust-lang.org/std/env/fn.home_dir.html). Sauf que la fonction est dépréciée dans la std parce que je cite "This function’s behavior may be unexpected on Windows". 
Il recommande d'aller voir pour une autre crate sur crates.io., j'ai cherché un peu mais je ne trouvais pas juste ce que je voulais ("résoudre un chemin") 

Du coup j'ai fini par le faire moi même. Tu peux retrouver [ma fonction ici](https://github.com/glcraft/aio/blob/main/src/main.rs#L25-L35). Tu remarqueras, elle ne fait pas plus que ce qu'on lui demande 😂
